name: Build

on:
  push:
    branches: [ XeSS, 'release/**' ]
  pull_request:
    branches: [ XeSS, 'release/**' ]

jobs:
  build-windows:
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - build-flavour: debug
            output-subdir: _Comp64Debug
          - build-flavour: debugoptimized
            output-subdir: _Comp64DebugOptimized
          - build-flavour: release
            output-subdir: _Comp64Release

    steps:
    - name: Setup variables
      uses: actions/github-script@v7
      with:
        script: core.exportVariable('GITHUB_SHA_SHORT', context.sha.substring(0, 7))

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Meson
      run: pip install meson==0.62.1
    
    - name: Setup XeSS SDK
      run: |
        mkdir -p XeSS_SDK_2.0.1/inc
        # Create placeholder header files to satisfy the include requirements
        # This is useful if you just need to compile without actually using XeSS functionality
        cat > XeSS_SDK_2.0.1/inc/xess.h << 'EOF'
        // Placeholder XeSS header file
        #pragma once
        #define XESS_API
        typedef enum { XESS_INITIALIZED = 0 } XeSSStatus;
        EOF
        
        # Adjust include path in meson.build if needed
        sed -i 's|../../../../../XeSS_SDK_2.0.1/inc|./XeSS_SDK_2.0.1/inc|g' src/dxvk/meson.build
        
        # Verify the directory structure
        ls -la XeSS_SDK_2.0.1/inc/

    - name: Build
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        . .\build_common.ps1
        PerformBuild -BuildFlavour ${{matrix.build-flavour}} -BuildSubDir ${{matrix.output-subdir}} -Backend ninja -EnableTracy false copy_output
    
    - name: Copy readme
      run: copy artifacts_readme.txt _output
    
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: dxvk-remix-${{env.GITHUB_SHA_SHORT}}-${{github.run_number}}-${{matrix.build-flavour}}
        path: |
          _output\*.dll
          _output\*.pdb
          _output\*.txt
          _output\usd\*
